### ISSUE TITLE
The `fod-export` and `ssc-export` actions do not cater for Application/Release names with spaces in.

### ISSUE THREAD

**Issue by kadraman** [fortify/github-action#15]
Given the following:

```
    - name: Export FoD vulnerability data to GitHub
      uses: fortify/github-action/fod-export@v1
      env:
        FOD_URL: ${{ inputs.fod_url }}
        FOD_CLIENT_ID: ${{ inputs.fod_client_id }}
        FOD_CLIENT_SECRET: ${{ inputs.fod_client_secret }}
        FOD_RELEASE: ${{ format('{0}:{1}', inputs.fod_app_name, inputs.fod_release_name) }}
```

if `inpus.fod_app_name` is "IWA-Java [KAL]" and `inputs.fod_release_name` is "main" the resultant `FOD_RELEASE` will be `'IWA-Java [KAL}:main'` (including single quotes). This should work fine.

However, the `fod-export` action doesn't see this and ends up trying to export all of the vulnerabilities for each release under "IWA-Java [KAL]".

Workaround is to use `FOD_RELEASE` with release id - the value of which can be retrieved using "fcli":

```
RELID=$(fcli fod release get "IWA-Java [KAL]:main" -o expr="{releaseId}")
echo "release_id=${RELID}" >> $GITHUB_OUTPUT
```

Note: the `ssc-export` as well as `fod-sast-scan` and `sc-sast-scan` might exhibit the same behaviour.
