### ISSUE TITLE
Allow setting up of ScanCentral Client v23.2.0

### ISSUE THREAD

**Issue by crance** [fortify/github-action#22]
Fortify version 23.2 has been released, however `fortify/github-action/setup@v1` does not support the setting for `sc-client: 23.2.0`.

It seems this is related to the code from [fcli](https://github.com/fortify/fcli/blob/51861c819db4b575accf4d897cd78b8840c358ed/fcli-core/fcli-tool/src/main/resources/com/fortify/cli/tool/sc-client/sc-client.yaml) which only allowed selected versions specified in this code.
```
defaultDownloadUrl: https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_{toolVersion}_x64.zip
defaultVersion: 23.1.0
versions:
  - version: 23.1.0
    digest: SHA-256:012e00fab914495ad235e8658207702869e02fffbd4d2adfcc3c2baf50fe8de9
  - version: 22.2.1
    digest: SHA-256:1b63e4e8bb0f9314d7ad1b0b925b0fbf878bfa37a1436774357de36fefbeeedf
```

Error Message:
![image](https://github.com/fortify/github-action/assets/31661897/a40126e8-afbe-4390-b03d-928b95e7103f)
