### ISSUE TITLE
Support for manual packaging when `scancentral package` fails or not appropriate

### ISSUE THREAD

**Issue by kadraman** [fortify/github-action#71]
### Enhancement Request

There are some instances where the manual creation of a Zip package is required, rather than using the `scancentral package` command. This could be because files cannot be included/excluded easily or the command fails. It would be good to allow the github-action to exclude packaging, e.g.:

```
      uses: fortify/github-action@v1
      with:
        sast-scan: true
        package: false
```

or similarly using a `DO_PACKAGE` option.
